files:
  include:
    - './**/*.scss'
  ignore:
    - './public/assets/css/plugin/*.scss'
    - './node_modules/**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero:
    - 0
    - convention: zero
  brace-style:
    - 2
    - allow-single-line: true
  clean-import-paths:
    - 0
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 0
    - include: true
  force-attribute-nesting: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase


  indentation:
    - 2
    - size: 2
  leading-zero:
    - 0
    - include: false
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 3
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0

  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 0

  no-trailing-zero: 0
  no-transition-all: 0
  no-url-protocols: 2
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  property-sort-order: 0
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 0
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 0
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 1
  url-quotes: 0
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  zero-unit: 0
