version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ptpadan1246/ubuntu-chrome-node-go:latest
        environment:
          DOCUMENT_ENV: test
          CIRCLE_TEST_REPORTS: /tmp/test-results
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_PASSWORD:
          MYSQL_DATABASE: circle_default
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    steps:
      - checkout
      - run: mkdir -p $GOPATH
      - run: cd $GOPATH && git clone https://github.com/YasushiKobayashi/go-api.git ./
      - run: curl https://glide.sh/get | sh
      - run: cd $GOPATH/src/app/config && mv sample.tml config.tml
      - run: cd $GOPATH/src/app && glide install
      - run: cd $GOPATH/src/app && go build main.go
      - run:
          command: $GOPATH/src/app/main
          background: true
      - run: cd src && mv config.sample.js config.js
      - run: npm rebuild node-sass
      - run: yarn
      - run: npm run lint
      - run: npm run flow
      - run: npm run build
      - run: npm run test
      - run: npm run server
      - run: python selenium/test_webdriver.py
      - run: mkdir -p $CIRCLE_TEST_REPORTS
      - run: cp selenium/log/* $CIRCLE_TEST_REPORTS
      - run: cp $GOPATH/src/app/log/* $CIRCLE_TEST_REPORTS
      - store_test_results:
          path: /tmp/test-results
