version: 2
jobs:
  build:
    working_directory: ~/webproject/document
    docker:
      - image: ptpadan1246/ubuntu-chrome-node-go
    steps:
      - checkout
      - run: cd src && mv config.sample.js config.js
      - run: npm i -g yarn mocha
      - run: yarn
      - run: npm run lint
      - run: npm run flow
      - run: npm run build
      - run: npm run test
      - run: npm run server

