version: 2
jobs:
  build:
    working_directory: ~/webproject/document
    docker:
      - image: circleci/node:8.1.0
    steps:
      - checkout
      - run: echo "hello world"
      - run: cd src && mv config.sample.js config.js
      - run: yarn
      - run: npm run lint
      - run: npm run flow
      # - run: npm run test
      - run: npm run build
      - run: npm run server

